package constant


const (
	STATUS_TELEPHONE        = "TELEPHONE"
	STATUS_VERIFY           = "VERIFY"
	STATUS_COMPLETE         = "COMPLETE"
	STATUS_INFORMATION      = "INFORMATION"
	TYPE_REGISTER_FACEBOOK  = "FACEBOOK"
	TYEP_REGISTER_GMAIL     = "GMAIL"
	TYPE_REGISTER_LINE      = "LINE"
	TYPE_REGISTER_TELEPHONE = "TELEPHONE"
)
