package constant

const (
	TYPE_VERIFY_REGISTER        = "REGISTER"
	TYPE_VERIFY_FORGET_PASSWORD = "FORGET_PASSWORD"
	TYPE_SYSTEM_SMS             = "SMS"
	TYPE_SYSTEM_EMAIL           = "EMAIL"
	STATUS_VERIFY_SUCCESS       = "SUCCESS"
	STATUS_VERIFY_FAIL          = "FAIL"
	STATUS_VERIFY_PENDING       = "PENDING"
)
